#'#docker run -d --name mongodb -e MONGO_INITDB_ROOT_USERNAME': admin -e MONGO_INITDB_ROOT_PASSWORD
spring:
  data:
    mongodb:
      authentication-database: GlobalAPIDB
      username: uatuser
      password: uatuser
      database: GlobalAPIDB
      port: '27017'
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
